
logging.level.root=WARN
logging.level.com.example.addressbook=ERROR

logging.file.name=logs/prod-addressbook.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [PROD] %level %msg%n

spring.jpa.show-sql=false